### ISSUE TITLE
unable to publish to npm via lerna

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-ui#89]
running npm run publish leads to this error:

```bash
lerna ERR! Error: Command failed: git add -- package/package.json lerna.json
lerna ERR! The following paths are ignored by one of your .gitignore files:
lerna ERR! package
lerna ERR! Use -f if you really want to add them.
lerna ERR! 
lerna ERR!     at makeError (/Users/cezaraugusto/dev/brave-ui/node_modules/@lerna/child-process/node_modules/execa/index.js:172:9)
lerna ERR!     at Promise.all.then.arr (/Users/cezaraugusto/dev/brave-ui/node_modules/@lerna/child-process/node_modules/execa/index.js:277:16)
lerna ERR!     at <anonymous>
lerna ERR! Error: Command failed: git add -- package/package.json lerna.json
lerna ERR! The following paths are ignored by one of your .gitignore files:
lerna ERR! package
lerna ERR! Use -f if you really want to add them.
lerna ERR! 
lerna ERR!     at makeError (/Users/cezaraugusto/dev/brave-ui/node_modules/@lerna/child-process/node_modules/execa/index.js:172:9)
lerna ERR!     at Promise.all.then.arr (/Users/cezaraugusto/dev/brave-ui/node_modules/@lerna/child-process/node_modules/execa/index.js:277:16)
lerna ERR!     at <anonymous>
lerna ERR! lerna Command failed: git add -- package/package.json lerna.json
lerna ERR! lerna The following paths are ignored by one of your .gitignore files:
lerna ERR! lerna package
lerna ERR! lerna Use -f if you really want to add them.
lerna ERR! lerna 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave-ui@0.0.0 publish: `npm run build && lerna publish`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the brave-ui@0.0.0 publish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cezaraugusto/.npm/_logs/2018-08-22T02_19_30_213Z-debug.log

```

seems related to latest change on package publishing cc @NejcZdovc

**Comment by baishengmei** [comment]
Excuse me! Do you resolve the question? I have the same question.
